apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: manuela-ci

resources:
# Uncomment this Pipeline to start the parallel pipeline that requires RWX PVCs to run the tasks.
#- seed-run.yaml
# Seed PipelineRuns to build individual component images using RWO PVCs
#- seed-iot-anomaly-detection-run.yaml
#- seed-iot-consumer-run.yaml
#- seed-iot-frontend-run.yaml
#- seed-iot-software-sensor-run.yaml
