# Format of .dockerconfigjson is the base64 encode "auths" dictionary
#
#{
#  "auths": {
#    "quay.io": {
#      "auth": "SU1BR0VfUkVHSVNUUllfVVNFUjpJTUFHRV9SRUdJU1RSWV9QQVNTV09SRA==",
#      "email": ""
#    }
#  }
#}
# auths["quay.io"]["auth"] is a base64 encoded string of IMAGE_REGISTRY_USER:IMAGE_REGISTRY_PASSWORD
kind: List
apiVersion: v1
items:
- kind: Secret
  apiVersion: v1
  metadata:
    name: quay-build-secret
  data:
    .dockerconfigjson: |
      DOCKERCONFIGJSON
  type: kubernetes.io/dockerconfigjson
