apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-redis-ha-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-access-role
subjects:
- kind: ServiceAccount
  name: argocd-redis-ha