apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- installplan-approver-service-account.yaml
- installplan-approver-role.yaml
- installplan-approver-rolebinding.yaml
- installplan-approval-job.yaml
